### PR TITLE
[PLUGIN-947] docs xml correction

### PR DESCRIPTION
**Pull request by sumitnigamcs**
docs xml correction

### CODE REVIEW

**Comment by sumitnigamcs** [comment]
@rmstar Please review this PR for bug PLUGIN-947

**Review by rmstar — APPROVED** [review]
please fix merge conflict

**Comment by sumitnigamcs** [comment]
> please fix merge conflict

done @rmstar

**Comment by rmstar** [comment]
please squash commits

**Comment by sumitnigamcs** [comment]
> please squash commits

one of it is a merge commit, so couldn't squash. Any suggestions on this?

**Comment by rmstar** [comment]
`git rebase -i develop`, then squash

**Comment by sumitnigamcs** [comment]
> `git rebase -i develop`, then squash

done @rmstar   CC: @itsankit-google

**Pull request merged**
