### PR TITLE
Added containsMacro check if schema provided by macro

### PR DESCRIPTION
**Pull request by sanket2000**
Fixed: Http Batch Source, Macro schema not working #132

### CODE REVIEW

**Comment by bhumitech-cloud** [comment]
Hii

**Comment by bhumitech-cloud** [comment]
Looks good

**Comment by sanket2000** [comment]
Hi @MrRahulSharma 
Does this repo accept public PR?

**Review by MrRahulSharma — APPROVED** [review]
LGTM

**Comment by sanket2000** [comment]
Closing this PR #133 and Issue #132 because they were handled in new PR #134

**Pull request closed without merging**
